version: '2'

services:
  app:
    build: .
    #command: npm start
    volumes:
      - .:/app
    ports:
      - "6000:3000"
    depends_on:
      - mongodb-dev
  mongodb-dev:
    image: 'mvertes/alpine-mongo'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data_dev:/bitnami'

  mongodb-test:
    image: 'mvertes/alpine-mongo'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27018:27017"
    volumes:
      - 'mongodb_data_test:/bitnami'

volumes:
  mongodb_data_dev:
    driver: local
  mongodb_data_test:
    driver: local
